name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: 'Random number'
    value: ${{ steps.generate-random-number.outputs.random-number }}
runs:
  using: 'composite'
  steps:
    - name: Set Greeting
      run: echo "Hello, ${{ inputs.who-to-greet }}."
      shell: bash
    
    - name: Generate random number
      id: generate-random-number
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash