name: Reusable Workflow Demo

on:
  workflow_dispatch:
  
jobs:
  call-reusable-workflow-path:
    name: Invoke reusable workflow using path
    uses: ./.github/workflows/12-reusable-caller-workflow.yaml
    with:
      foo: bar
      environment: staging
    secrets: inherit